### PR TITLE
Stretched the background instead of maintaining its aspect ratio

### PR DESCRIPTION
**Pull request by radujipa**
Related to https://github.com/KanoComputing/Kerberos/issues/13

### CODE REVIEW

**Comment by radujipa** [comment]
@tom @pazdera could you please review?

**Comment by pazdera** [comment]
@radujipa I think this might mess up the positioning of some items to the background if you stretch it to a different aspect ratio -- like the button on the audio screen or the judoka on the wifi screen.

**Comment by radujipa** [comment]
@pazdera I totally agree. I've tested this on 16:10 aspect ratio and the Screen Kit and it works ok. I asked @tombettany to do a test on a very wide screen.

**Comment by radujipa** [comment]
I've tested this with quite a few resolutions and aspect ratios: 21:9, 8:5, 5:4, 3:2 .. And I haven't had any problems.

**Comment by radujipa** [comment]
Merging this at the end of the day for testing if there are no other objections.

**Comment by radujipa** [comment]
@FMog assigning this to you for testing. Sorry for the ticket being where it is, but what was happening is this: during the init-flow, on our Samsung screens in the office (1920x1200, 19:10 aspect ratio), the background had black lines above and below it. We initially thought it was an overscaned, but it turned out to just the background resizing itself to 16:9 or 4:3 aspect ratios. I have changed this here to expand to the full size of the screen as to not to mislead users to make incorrect Overscan settings. Tricky bit is that _it might_ mess up positioning of speech bubbles, assets, and stuff. I've tested this on numerous resolutions and it seemed to cope well enough. Sorry for the long rant. :)

**Comment by pazdera** [comment]
@radujipa I'm surprised that the positions aren't buggered up, but there's probably something I'm missing. I'll give it a quick test as well with 16:10.

**Pull request merged**
